/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CouponsShop {
        "targetURL": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ShippingForm {
        "onsubmitted": Function;
    }
}
declare global {
    interface HTMLCouponsShopElement extends Components.CouponsShop, HTMLStencilElement {
    }
    var HTMLCouponsShopElement: {
        prototype: HTMLCouponsShopElement;
        new (): HTMLCouponsShopElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLShippingFormElement extends Components.ShippingForm, HTMLStencilElement {
    }
    var HTMLShippingFormElement: {
        prototype: HTMLShippingFormElement;
        new (): HTMLShippingFormElement;
    };
    interface HTMLElementTagNameMap {
        "coupons-shop": HTMLCouponsShopElement;
        "my-component": HTMLMyComponentElement;
        "shipping-form": HTMLShippingFormElement;
    }
}
declare namespace LocalJSX {
    interface CouponsShop {
        "targetURL"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ShippingForm {
        "onsubmitted"?: Function;
    }
    interface IntrinsicElements {
        "coupons-shop": CouponsShop;
        "my-component": MyComponent;
        "shipping-form": ShippingForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "coupons-shop": LocalJSX.CouponsShop & JSXBase.HTMLAttributes<HTMLCouponsShopElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "shipping-form": LocalJSX.ShippingForm & JSXBase.HTMLAttributes<HTMLShippingFormElement>;
        }
    }
}
