/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CouponsShop {
        "targetURL": string;
    }
    interface ShippingForm {
        "onsendasletter": Function;
        "onshowagbs": Function;
        "onsubmitted": Function;
    }
}
declare global {
    interface HTMLCouponsShopElement extends Components.CouponsShop, HTMLStencilElement {
    }
    var HTMLCouponsShopElement: {
        prototype: HTMLCouponsShopElement;
        new (): HTMLCouponsShopElement;
    };
    interface HTMLShippingFormElement extends Components.ShippingForm, HTMLStencilElement {
    }
    var HTMLShippingFormElement: {
        prototype: HTMLShippingFormElement;
        new (): HTMLShippingFormElement;
    };
    interface HTMLElementTagNameMap {
        "coupons-shop": HTMLCouponsShopElement;
        "shipping-form": HTMLShippingFormElement;
    }
}
declare namespace LocalJSX {
    interface CouponsShop {
        "targetURL"?: string;
    }
    interface ShippingForm {
        "onsendasletter"?: Function;
        "onshowagbs"?: Function;
        "onsubmitted"?: Function;
    }
    interface IntrinsicElements {
        "coupons-shop": CouponsShop;
        "shipping-form": ShippingForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "coupons-shop": LocalJSX.CouponsShop & JSXBase.HTMLAttributes<HTMLCouponsShopElement>;
            "shipping-form": LocalJSX.ShippingForm & JSXBase.HTMLAttributes<HTMLShippingFormElement>;
        }
    }
}
